---
virtualmachines:
  - name: "selinux1"
    image: "rhel-10-0-07-09-25-2"
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
