
---
virtualmachines:
  - name: "rhel"
    image: "rhel-9.5"
    bootloader: efi
    memory: "2G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
#    packages:
#      - policycoreutils
